# Компилятор и флаги
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++11 -O2

# Имена файлов
SOURCES = main.cpp complex.cpp sort.cpp
OBJECTS = $(SOURCES:.cpp=.o)
TARGET = complex_sort

# Цель по умолчанию
all: $(TARGET)

# основной программы
$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJECTS)

# Компиляция отдельных .cpp файлов
main.o: main.cpp complex.h sort.h
	$(CXX) $(CXXFLAGS) -c main.cpp

complex.o: complex.cpp complex.h
	$(CXX) $(CXXFLAGS) -c complex.cpp

sort.o: sort.cpp sort.h complex.h
	$(CXX) $(CXXFLAGS) -c sort.cpp


clean:
	rm -f $(TARGET) $(OBJECTS)


.PHONY: all clean
